### ISSUE TITLE
Error if repo_dir and package name don't agree

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [TDKorn/sphinx-readme#11]
Hi, as I'm checking out your package, I run into a bug.

It is on Line 52 of `utils/linkcode.py`:

https://github.com/TDKorn/sphinx-readme/blob/0a5fe5d7ed6af950beaeb4b32febcccffdad4171/sphinx_readme/utils/linkcode.py#L52C5-L52C5

```python
    repo_dir = get_repo_dir()
    pkg = pkg_resources.require(repo_dir.name)[0]
```

My project's dir name and Python package aren't the same. Hence, using the `repo_dir` to search for the package failed with the `pkg_resources.DistributionNotFound` exception.

<del>It has been a while since I last wrote a Sphinx extension, but I think there is a way to get the Python package name from Extension API. Basically, accessing the information Sphinx's autodoc uses.</del>

update (12/12): Spent a bit of time deep-diving the code, and what it appears to need is a `conf.py` variable (something like `readme_repo_package`) and present its value to `pkg_resources.require()` if given, else use the current auto-detected package name. What do you think?

**Comment by TDKorn** [comment]
Hey @tikuma-lsuhsc! Sorry for the delay, this should be fixed in `v1.1.2` - please try it out and let me know if you're still having issues! I tested it out on `ffmpegio` and was able to generate the `index.rst` file with the new bug fixes

**Comment by tikuma-lsuhsc** [comment]
@TDKorn  - Cool. Thanks for addressing the issue. I am considering to use it for a (currently) internal project, which is different from `ffmpegio` but thanks for testing anyway! I'll check out the update tonight (in the US).

Meanwhile, I'm going a bit off topic, but does this extension work with `autodoc` too? As in embedding the documentation on the readme (useful for small repos, and kinda what I am looking for)

**Comment by TDKorn** [comment]
@tikuma-lsuhsc right now autodoc directives aren't replaced by the extension, sorry. I've looked into it and it seems possible, although a bit complicated to fully implement due to all the options and potential usages. I can try though!
